### PR TITLE
chore(deps): upgrade to ember-data v4.12.0

### PR DESCRIPTION
**Pull request by derrabauke**
Fixes
> Could not find module `@ember/error` imported from `@ember-data/adapter/error`

More info see: https://github.com/emberjs/data/pull/8422

### CODE REVIEW

**Comment by derrabauke** [comment]
Failing cause of https://github.com/embroider-build/embroider/issues/1077

**Comment by derrabauke** [comment]
> Failing cause of [embroider-build/embroider#1077](https://github.com/embroider-build/embroider/issues/1077)

Upgrading `ember-data` only to `v4.7.2` prevents us from this.

**Comment by anehx** [comment]
> Failing cause of [embroider-build/embroider#1077](https://github.com/embroider-build/embroider/issues/1077)

That issue is long resolved, we just need to use the alpha version of `ember-cli-mirage` as we do in other repos..

**Comment by derrabauke** [comment]
[Fix on the way](https://github.com/mainmatter/ember-simple-auth/pull/2542/files) - But probably we have to upgrade to ember-simple-auth v5 first. Don't think they will back-port it.

**Comment by anehx** [comment]
Closed in favor of #763

**Pull request closed without merging**
